In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [3]:
df=pd.read_csv('Preprocessing Tutorial Part 1/data.csv')

In [4]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [6]:
X=df.iloc[:, : -1].values
y=df.iloc[:, -1].values

In [7]:
X,y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

In [8]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [9]:
# solution 1: drop the rows with null values
df_dropna=df.dropna()
df_dropna.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [10]:
# solution2: fill the null values with mean of the column
df_fillna=df.fillna(df.mean(numeric_only=True))
df_fillna.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [11]:
# solution 3: scikit-learn's SimpleImputer
from sklearn.impute import SimpleImputer

In [12]:
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
X[:,1:3]=imputer.fit_transform(X[:,1:3])

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
# one-hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [16]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [17]:
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [18]:
encoder_np=pd.get_dummies(df,columns=['Country'],dtype=int)

In [19]:
encoder_np

    Age   Salary Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0        No               1                0              0
1  27.0  48000.0       Yes               0                0              1
2  30.0  54000.0        No               0                1              0
3  38.0  61000.0        No               0                0              1
4  40.0      NaN       Yes               0                1              0
5  35.0  58000.0       Yes               1                0              0
6   NaN  52000.0        No               0                0              1
7  48.0  79000.0       Yes               1                0              0
8  50.0  83000.0        No               0                1              0
9  37.0  67000.0       Yes               1                0              0

In [20]:
from sklearn.preprocessing import  LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
print(X_test,y_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]] [0 1]

In [23]:
print(X_train,y_train)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]] [1 0 1 0 1 1 0 0]

In [24]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train[:,3:]=ss.fit_transform(X_train[:,3:])
X_test[:,3:]=ss.transform(X_test[:,3:])

In [26]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
X_train[:,3:]=mms.fit_transform(X_train[:,3:])
X_test[:,3:]=mms.transform(X_test[:,3:])